project_name: pocketblocks

dist: .builds

before:
  hooks:
    - go mod tidy

builds:
  # used only for tests
  - id: build_cgo
    main: ./server/main.go
    binary: pocketblocks
    ldflags:
      - -s -w -X github.com/internoapp/pocketblocks.Version={{ .Version }}
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64

  - id: build_noncgo
    main: ./server/main.go
    binary: pocketblocks
    ldflags:
      - -s -w -X github.com/internoapp/pocketblocks.Version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm

archives:
  - id: archive_noncgo
    builds: [build_noncgo]
    format: zip
    files:
      - LICENSE*
      - CHANGELOG*

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
