name: Release new version

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_USER: ${{ github.actor }}
  GH_TAG: ${{ github.ref_name }}
  PBL_VERSION: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Change Version
        run: echo "${GH_TAG}" | cut -c 2- > ./client/VERSION
      - name: Build Client
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0
      - run: cd proxy && yarn run build:ci
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.21.3"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --skip=validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Publish Package
        run: chmod +x ./docker-build.sh && ./docker-build.sh
